name: 'Prevent GitHub PRs'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          pr-comment: >
            This repository does not accept pull requests,
            see the README for details.